### ISSUE TITLE
tynamo-federatedaccounts-pac4jbasedoauth-0.5.0 depends on way too old pac4j-oauth 1.4.1

### ISSUE THREAD

**Issue by jevgenitolstouhhov** [tynamo/tynamo-federatedaccounts#3]
Hi! As you can see from the subj, we have a dependency on pac4j-oauth 1.4.1, which contains old org.pac4j.oauth.client.FacebookClient. The problem with this FacebookClient is that it tries to request "username" attribute, but Facebook has changed the API some time ago. This ends up in an error response from facebook: 
"Failed to retrieve data / failed code : 400 and body : {"error":{"message":"(#12) username field is deprecated for versions v2.0 and higher","type":"OAuthException","code":12,"fbtrace_id":"EnInE13o8s9"}}"

Later versions of pac4j-oauth, like 1.8.2, have FacebookClient fixed. Can we make tynamo-federatedaccounts-pac4jbasedoauth-0.5.0 depend on  pac4j-oauth 1.8.2 instead of 1.4.1?  Thanks!

**Comment by kaosko** [comment]
Yes, I know. This is next on my list as I need it myself but maybe take a few weeks unless somebody sends a pull request first.

**Comment by kaosko** [comment]
Implemented in #4. I'd like to at least update restfb-native module before making a new release.

**Comment by jevgenitolstouhhov** [comment]
Thank you very much Kalle! :)
